[package]
name = "mrt"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.17", features = ["derive"]}
colored = "2.0.0"
regex = "1.6.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
